# Generated by Django 5.0.1 on 2024-01-29 00:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("beerlist", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beer",
            name="brewery",
        ),
    ]
