# Generated by Django 5.0.1 on 2024-01-29 00:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beerlist", "0002_remove_beer_brewery"),
    ]

    operations = [
        migrations.AddField(
            model_name="beer",
            name="brewery",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
